### ISSUE TITLE
obssim_smp_pairs in PstFromFlopyModel class

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#113]
What is the file order of obssim_smp_smp pairs? I guess it is ['actual_obs.dat', 'model_generated_obs.dat']. However, the generated pst file actually contains observations from the model_generated_obs.dat. If I switch the order, the obs values will be consistent. But actual_obs.dat will be written to the *model input/output section in the pst file.

**Comment by jtwhite79** [comment]
You are correct - the instruction file is being written for the simulated smp, which is correct since this is the file that needs to be read after each model run.  At this point, its up to you to get the observed smp value into the control file `* observation data`.  I'll see if I can get something added to set those values automatically.
