### ISSUE TITLE
Best way to add drain cells to obs file

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#114]
This is a follow on from a previous issue, but probably different enough to warrant its own heading...

I'm trying to add drain cells to my observations. The problem is that they will be vaguely historically matched against three separate drain gauges that aggregate drainage from a couple of hundred drain cells each. They are not sfr reaches, so I can't use this (they are numbered by row,col, not reach, and they are not really head cells because they are aggregated to three locations.

I've tried a few approaches to this, but can't aggregate them before adding them to setup_hds_timeseries. Have I missed anything? I thought perhaps a dictionary of many kij instances would work, but I don't think I can get setup_hds_timeseries working with a dictionary {drn_gauge: [[k,i,j],[k,i,j],[k,i,j]]} rather than the usual {flux_location1: [k,i,j], flux_location2: [k,i,j], flux_location3: [k,i,j]}

I'm currently trying to aggregate the fluxes afterwards to be used as obs and forecasts, and kind of drowning a bit. Any hints on the best way of doing this?

**Comment by jtwhite79** [comment]
That time series setup routine currently just extracts the values from the cbb file for a single cell at a time.  The simplest solution is probably to inject an additional post-processor call into the forward run script to load the dataframe that the time series processor writes and aggregate the columns into a new column. If you don't care about the single cell DRN outputs, you could just overwrite the first column of the dataframe and save it with the same name - this will let you use the existing instruction file.  Otherwise, you'll need to write a new instruction file for these aggregated outputs.
