### ISSUE TITLE
Add a conditioned field generator to pyemu

### ISSUE THREAD

**Issue by hwreeves-USGS** [pypest/pyemu#120]
Jeremy, I'd like to add the conditional field generator to pyemu, and I'm wondering if you or other contributors have a preferred approach.  What I'm doing now is having the pest parameter be a seed value sent to the forward model and used in  `numpy.random.seed(value_from_pest)`.  That way the conditioned random field or fields used in the forward model can be re-generated.  I think the options are:

-  Add `draw_conditional` as a method to the SpecSim2d class, requires that the user's forward model makes a ss object.  You'd then pass a table of observation point locations and a factors file generated using the same geostructure as being used for interpolating from the pilot points to the MODFLOW grid and the observation locations. 

- Make a static method that would make a SpecSim2d object and then carry on.  This approach might make the forward model a bit cleaner, but it doesn't seem as efficient.  

I think in any case the user will want to generate the factors file before doing the forward run since that is such a time-consuming step.  I've tried the approach using the pilot-points as the observations points; but I plan to test it against a set of observation points that are not pilot points.
I'm using the conditioned fields for Monte Carlo testing, I haven't really thought about how they might be used in other analysis.

**Comment by jtwhite79** [comment]
That would be an awesome contribution!  It would be nice to generate a parameter ensemble where grid-scale and/or pilot point realized values are conditional on hard data. `pyemu.en.SEED` is a random seed that gets used in the ensemble classes, ok to use it for the specsim draws also?  As far as which approach to take, I like the idea of having it be seamless (where we gen the factors on the fly) but also have the option to pass a factors file since that can be slow as (still need to try to speed that up).  In any event, this sound great, so which ever way you wanna go is fine with me.

**Comment by hwreeves-USGS** [comment]
Looks like its close-  I need to test when the field is using log(K)
and maybe a little bigger domain -- I used the Freyberg model from
your class.

Money figures start on page 23

I hope to push the branch on Monday after the other testing.

HWR


Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________
