### ISSUE TITLE
Allow loading `.pst` file with incomplete sections

### ISSUE THREAD

**Issue by mnfienen-usgs** [pypest/pyemu#133]
On a project with multiple people on the team, we have one group working on parameters and another working on observations. So.....it would be really ideal to be able to create a PST object in pyemu with, for example, only parameter data. Currently, if there are no observations, pyemu will not load. It would be nice to allow it to load (thence to add observations to the object) and just throw a warning if the load results in an empty observations section. Possible?

**Comment by jtwhite79** [comment]
It’s probably possible now if you don’t pass a filename to the constructor and build up the components manually using the dtype and field name info in pst_utils.  I guess we could add an optional forgive arg similar to what’s in flopy but I’m wondering how common this use case is?  Or can the new ctl file fmt handle this more easily since everything is stored in ext csv files?
