### ISSUE TITLE
PstFrom apply_list_pars and pandas 1.1

### ISSUE THREAD

**Issue by jwhite-usgs** [pypest/pyemu#162]
@briochh - looks like some trouble is brewing with pandas 1.1.  The mfnwt freyberg PstFrom is bombing and its something to do with broadcasting a multiindex when applying the riv package list pars - yuck!  Can you check it out?

**Comment by briochh** [comment]
I'll take a look.

**Comment by briochh** [comment]
This issue seems to relate to a change in behaviour in pandas. Index.intersection() is now returning duplicated indices that intersect. I don't think this is a bug in pandas and perhaps this is more consistent with how duplicates are handled elsewhere. Duplicates in the intersection meant that we were double duplicating indices in that broadcast, not ideal! 
Anyway the #163 hopefully fixes this.

**Comment by jtwhite79** [comment]
Thanks B.  Looks good!
