### ISSUE TITLE
PyEMU for gw only and Wrong numpy version ?..... 

### ISSUE THREAD

**Issue by scalet98** [pypest/pyemu#167]
Hello ! 
I have two issues...

First issue is about the  numpy version error. 
In the requirement file, I think you have wrong package version for numpy, 
Because v1.19.1 for numpy is the most current one. :) 

numpy>=1.9 need to be changed into numpy>=1.19

requirement ----------------------------------
numpy>=1.9
pandas>=0.18.1
pyshp
codecov
coverage

Second issue... as I know you have surface water Pest sample in previous PEST version. 
For this time, didn't you develop python version PEST module for surface water model HSPF ? 
I am just curious about it. 

Thanks,
Jiheon

**Comment by jwhite-usgs** [comment]
Hey @scalet98 - I may be mistaken, but I think numpy version 1.9 is an older version, where 1.19 > 1.9.

On the topic of surface water models and PEST/pyEMU, pyEMU, like PEST, is model independent so it can be applied to "any" model that you can wrap PEST around.  There is some new functionality to help automate the PEST interface setup - that is in the `PstFrom` class.  Its been a while since I played with HSPF, but if you can get HSPF (or pyHSPF) to read and write list-type file and/or array type files, then you can use `PstFrom` to setup the PEST process for you.  There is an example notebook of using `PstFrom` with MODFLOW-6 in the examples.  Alternatively, I think PEST has some utilities to help with HSPF - those would be on the PEST home page website.
