### ISSUE TITLE
Linear analysis with log transformed parameters

### ISSUE THREAD

**Issue by jesshe** [pypest/pyemu#175]
Sorry if this is a naive question. 

I'm trying pyemu for some linear analysis on the parameters of a calibrated groundwater model. These parameters have been log transformed for PEST calibration, but I'm interested in looking at posterior confidence intervals for the non-transformed parameters. When calculating parameter variance from upper and lower bounds in the .pst, pyemu appears to use log transformed parameter boundary values. Why does it do this? This seems to imply that parameters follow a lognormal distribution, which breaks the assumption of normally distributed parameters. As a result it is not as simple to back calculate posterior confidence intervals (or even prior confidence intervals). Also, when I try to sample parameters for an ensemble using the .from_gaussian_draw() method, I get lognormal sample distributions.

From how I see it, parameter log transformation is useful during calibration, but an obstacle for this kind of uncertainty analysis. Is my best option to recalculate a jacobian with PEST using non-transformed calibrated parameter values, and then use pyemu without any transformation? Or is there a way of correctly working with log transformed parameters without that kind of hassle?

Many thanks in advance!
Jess

**Comment by jtwhite79** [comment]
Pretty solid question - I think there is a lot of confusion about the log transform and how it propagates thru these workflows.  As you say, using log transforms does help the parameter estimation problem mechanically by scaling and normalizing things.

But beyond helping with the parameter estimation problem, using log transform implies that in the prior parameter distribution (in a Bayesian sense), log-transformed parameter(s) follow a log-normal distribution(s) - If the parameter is defined by a log-normal distribution, then the estimated parameter value is conditional on this assumed distribution (this is why you get different estimated values if you change log transform).  Also, you must use log transform where appropriate because the linear analysis/FOSM in PEST(++) and pyEMU work in this space during calculations so that the Gaussian assumption holds. As you can see, the log transform has wide-ranging effects and implications in the PEST world.  For example, with parameter bounds, the distance between 1 and 100 is much different than the distance between log10(1) and log10(100) - this distance is used in both PEST(++) and pyEMU to approximate prior parameter uncertainty in the absence of any other user-supplied information.  Being consistent between the parameter estimation process and the follow-on uncertainty process(es) is critical because the entries in the Jacobian are also with respect to the log transform (the denominators/parameter perturbations use log transform status).  Geostatistical structure files also need to know about log transform.  

You can still back-transform the parameter confidence intervals, you just have to make sure you add/subtract standard deviations from initial or estimated parameter values in log space.  But there is a conceptual problem here: the log transform is a non-linear transform, which means the prior confidence interval in arithmetic space can be narrower than the posterior interval if the parameter value increases in magnitude during during estimation but the variance does change (much).  This is why PESTPP_GLM report prior and posterior intervals in log space for the  FOSM parameter summary.  

We could add functionality to report prior and posterior intervals (with flag to report in arithmetic space) to `Schur.get_parameter_summary()` if that would help.   Just need to be aware of the issues...

**Comment by jesshe** [comment]
Thanks for the clarification! Really helpful! 

Working with PEST previously, I just log transformed the parameters (seeing the shiny promise of better performance of estimation) without much thought on how it affects the underlying assumed probability distribution.

In a case where you believe parameters in arithmetic space are more appropriately described by normal distributions, would you recommend just working with non-transformed parameters all the time (through both estimation with PEST and linear uncertainty analysis with PyEMU)?

**Comment by jtwhite79** [comment]
> In a case where you believe parameters in arithmetic space are more appropriately described by normal distributions, would you recommend just working with non-transformed parameters all the time (through both estimation with PEST and linear uncertainty analysis with PyEMU)?

exactly - both PEST(++) and pyEMU will mix and match non-log and log parameter seamlessly under the hood for all the calculations that are sensitive to log status.  Just have to make sure the log (or not) transform for all parameters is consistent between the control file, Jacobian, and any aux files (like uncertainty files, covariance matrices, geostat structure files, etc)
