### ISSUE TITLE
Pilot Points Setup

### ISSUE THREAD

**Issue by Lau397** [pypest/pyemu#176]
_Hi there!_

_I'm trying to add some pilot points (MODFLOW 6) as follows:_

```
prefix_dict = {0:["hk0,"vk0"], 1:["hk1","vk1"], 2:["hk2","vk2"], 3:["hk3","vk3"]}
df_pp = pyemu.pp_utils.setup_pilotpoints_grid(ml=m,prefix_dict=prefix_dict, ibound=ibound,
                                              pp_dir=model_ws,
                                              tpl_dir=model_ws,
                                              every_n_cell=50, shapename="pp.shp"))
```
_On ibound I've tried these ways: m.dis.idomain.array, m.dis.idomain[0].array, m.npf.k.array, and much more... similar to all that (even ignoring the ibound part). The issue I've encountered is no matter how I try to put or not the ibound criteria it always throws this error:_

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-37-d3bb8577bb7f> in <module>
      
----> 5 df_pp_all = pyemu.pp_utils.setup_pilotpoints_grid(ml=m,prefix_dict=prefix_dict, ibound=ibound,
      6                                               pp_dir=model_ws,
      7                                               tpl_dir=model_ws,

~\anaconda3\lib\site-packages\pyemu\utils\pp_utils.py in setup_pilotpoints_grid(ml, sr, ibound, prefix_dict, every_n_cell, ninst, use_ibound_zones, pp_dir, tpl_dir, shapename, longnames)
     76         except Exception as e:
     77             raise ImportError("error importing flopy: {0}".format(str(e)))
---> 78         assert isinstance(ml, flopy.modflow.Modflow)
     79         sr = ml.sr
     80         if ibound is None:

AssertionError: 
``` 
_What am I doing wrong :(? Is this only useful for MF2005 so far? Also, **how can I put the ibound for all my four layers?** (please). I even tried to put it as a list of int arrays, since all my layers have different domain of course, but nothing yet seem to work :'(_

Ps. It did work like a week ago or so, while I was playing around with it to understand how to add my pilot points to all my model layers. It wasn't very successful (_lol_) but it ran fine for one layer anyway. I've been these two days trying again with the same code to get done what I need aaaaaand ...now it doesn't! 

_Any solution is very well received, thanks!_

**Comment by jtwhite79** [comment]
I think what is tripping you up is the assert on 78 to make sure the `ml` is a `flopy.modflow.Modflow` because that routine relies on `ml.sr` for spatial referencing. We probably need to update the code to use the `ModelGrid` attribute instead (and this should get you going thru with a flopy modflow6 model instance).  

If you want to do pilot points in multiple layers and/or with differing ibounds, then you need to make separate calls to the routine.   We could probably make this easier to do.  We probably also need to work on more general support for pilot points (at least for non-grid based spacings).

But!  if you are looking to get PEST(++) wrapped around a modflow6 model, the `PstFrom` class might be a easiest (and slickest!) way to get going - it includes support for setting up pilot points.  There is an example notebook here that shows how it works for a synthetic modflow6 model:

[https://github.com/pypest/pyemu/blob/develop/examples/pstfrom_mf6.ipynb](https://github.com/pypest/pyemu/blob/develop/examples/pstfrom_mf6.ipynb)

**Comment by nikobenho** [comment]
Hi,

Using this issue for a similar question:

How could one go about adding pilot points from a shapefile?

Thanks for your great work with this package!

Cheers

**Comment by jtwhite79** [comment]
@nikobenho - If you have a shapefile of your pilot point locations, you need get the pilot point info into a dataframe with `name`,`x`, and `y` attributes.  Then you can use the `OrdinaryKrige` class:

make a geostructure:
```
gs = pyemu.geostats.Geostruct(variograms=pyemu.geostats.ExpVario(a=1,contribution=1))
```
create an `OrdinaryKrige` instance (`df` is the dataframe with pilot point attributes):
```
ok = pyemu.geostats.OrdinaryKrige(gs,df)
```
calculate the interpolation factors for a given grid.  Here, `sr` is `pyemu.helpers.SpatialReference` instance that can be loaded from a pest grid spec file or `sr` can be a flopy modelgrid instance.  This step takes some time b/c its pure python...
```
ok.calc_factors_grid(sr)
```
Now save the factors to a pest-type factors file:
```
ok.to_grid_factors_files("my.fac")
```

You can also write your pilot points to a pilot points template file using that dataframe using `pyemu.pp_utils.pilot_points_to_tpl()`

**Comment by nikobenho** [comment]
Thanks for your response! I had an error occuring which i think originates from using the disv package rather than the dis package. I'm still learning MF6 and Flopy, so I apologize if I'm not able to provide sufficient information. 

The error was `Exception: spatial_reference does not have proper attributes:'VertexGrid' object has no attribute 'xcentergrid'`

I guess the best strategy for my case is to use `pyemu.pp_utils.pilot_points_to_tpl()`?

Cheers!

**Comment by jtwhite79** [comment]
The pilot point support in `PstFrom` now accepts a dataframe or shapefile of predefined pilot point locations, so you should be good to go now
