### ISSUE TITLE
Pst Class Modifies Control Data 

### ISSUE THREAD

**Issue by mrush-usgs** [pypest/pyemu#198]
Hello, I am using the Pst class to work with the parameter data section of my control file as a dataframe. When I go to write the updated control file, I have found that the control data section has also been modified, for example: 

illegal entry "noderforgive" is added on line 6: 
   1.000000E+01   2.000000E+00   1.500000E-01   1.000000E-03       100        30          lamforgive        noderforgive

contradictory entries added on line 10: 
         1         1         1         0          verboserec          reisaveitn          parsaveitn          parsaverun          parsaveitn        noparsaverun

Note that I am using beopest64.exe. Is there any way to avoid modifying the control data section? Thank you!

**Comment by jtwhite79** [comment]
Thats happening because pyemu doesnt yet handle all those additional control data options.  If you can post your control file, I'll see if I can get those additional options supported.

**Comment by mrush-usgs** [comment]
Thanks! I am able to avoid writing "noderforgive" by setting pst.control_data.derforgive = '' for example, but I haven't found a way to avoid writing "parsaveitn parsaverun parsaveitn noparsaverun"

[sm.zip](https://github.com/pypest/pyemu/files/5623946/sm.zip)

**Comment by jtwhite79** [comment]
sm.zip has "parsaveitn parsaverun parsaveitn noparsaverun" - did you not want those to be written?

**Comment by mrush-usgs** [comment]
Ideally just the first set would be written (parsaveitn parsaverun)

**Comment by jtwhite79** [comment]
As of #199, This should be all fixed up know.  Let us if not.

**Comment by Cecile-A-C** [comment]
Hello,

I have a related issue (but I can open a new issue if that's better!). I am copying a pest control file, reading it with pyemu.Pst and writing it again (to include some new modifications):
```
shutil.copy('pestpp_old.pst', 'pestpp_new.pst')
pst = pyemu.Pst('pestpp_new.pst')
pst.write('pestpp_new.pst')
```
The control data section in the updated control file has been modified (many variables are now left out).
_'pestpp_old.pst'_:
![image](https://user-images.githubusercontent.com/59694240/156069637-51fa401d-0a4c-4855-8e5b-201a5b0944ac.png)

vs _'pestpp_new.pst'_:
![image](https://user-images.githubusercontent.com/59694240/156069853-887bb436-385c-417f-9e27-418b6d1da12a.png)

The updated control file _'pestpp_new.pst'_ no longer passes PESTCHEK, because NUMCOM is missing (but the original control file _'pestpp_old.pst'_ passed PESTCHEK with no errors):
![image](https://user-images.githubusercontent.com/59694240/156069242-681af7cc-cfc2-4afc-8648-90cff6e5d60a.png)

Is there something I could do? Here are my files: [test.zip](https://github.com/pypest/pyemu/files/8157328/test.zip)

Thank you!

**Comment by jtwhite79** [comment]
Those optional args in the control data section are a pain!  I've got a fix for your issue testing now...

**Comment by Cecile-A-C** [comment]
Great, thanks!

**Comment by jtwhite79** [comment]
Ugh!  This control data stuff is rough.  I'll take a look...

**Comment by Cecile-A-C** [comment]
Hi again! Sorry, I found another issue with the control data section... It's still when I use pyemu.Pst.from_io_files():
```
pst = pyemu.Pst.from_io_files(tpl_files, in_files, ins_files, out_files)
pst.write('test.pst')
```
This is the header that is generated:
![image](https://user-images.githubusercontent.com/59694240/167057414-fe42da72-43ab-402c-9d33-8e7e148856df.png)
And now PESTCHEK gives me a new error: 
![image](https://user-images.githubusercontent.com/59694240/167057447-fabfce06-4493-4597-9d76-3621104d8cb0.png)
I can correct this manually, but I just thought I'd mention it (I'm using the develop branch).

**Comment by javgs-bd** [comment]
> I think the strategy for those optional vars in both `* parameter groups` and `* regularization` is to be explicit by setting values that are either default or to help users get the best options set...generally its hard to deal with these optional args!

Hi @jtwhite79 I've been trying to workaround this by manually tweaking the pst files. However, while I understand the logic of best options and the difficulty of dealing with optional args, I guess the main problem of the modifications to the pst file I get by using the PST constructor is that they interfere with a defense for reproducibility of the inverse problem. The user would have to ensure that none of the extra modifications alter the behavior of the inverse problem, beyond what he/she has changed by code. 

I wonder if there is any PST handler within pyemu that would ensure the only change to the pst file is the one coded by the user, or if this would merit a feature request/opening an issue?

**Comment by jtwhite79** [comment]
generally we do just that - `Pst` retains user input files if specified.  Where things are hard in the `control data` because that section continues to evolve in PEST(_HP) in increasingly nonlinear ways (like if some arg is provided, then additional args are expected - see @Cecile-A-C  screen shot error from pestchek...).  Im trying to keep up but at some point this would be soooo much easier if PEST(_HP) supported the version 2 ctl file!

**Comment by javgs-bd** [comment]
Hi, Is there a magical line (like in flopy) to install the dev branch? or should I try what it is suggested here?:
https://community.spiceworks.com/topic/2241841-how-do-you-install-a-dev-branch-from-github

I tried the modified flopy version but I still see the same version of pyemu in pip list
(pip install https://github.com/pypest/pyemu/zipball/develop)

**Comment by jtwhite79** [comment]
I think its like this:

` pip install git+https://github.com/pypest/pyemu@develop`
