### ISSUE TITLE
MF6 readability ?

### ISSUE THREAD

**Issue by leeaender** [pypest/pyemu#212]
Hello everybody,
I'm struggeling getting pyEMU working for my MODFLOW 6 model.

The example (pstfrom_mf6.ipynb) uses unformated txt files to get the properties and stress period data into the pyEMU environement with an 'OPEN/CLOSE' command. 
Is there a possibility to make pyEMU read MODFLOW 6 files directly? (and adress e.g. leakage in RIV directly) Or do I have to reformat the MODFLOW 6 files?

Many thanks! I hope it's ok, to post this question here...
Leander

**Comment by jtwhite79** [comment]
@leeaender - that is good question.  By design, `PstFrom` works with array and list files so that it can be independent of the underlying model (beyond MF6 and even MODFLOW generally). The precursor to `PstFrom` (`PstFromFlopyModel`) is "hardwired" to the MODFLOW-5 family and that is fine because it was a first-attempt and also the MODFLOW-5 family needs that level of specialization to handle the "special" file formats (hah!).  There are some flags in flopy to help get an MF6 model into fully external format so that `PstFrom` can be used.  There are `sim.simulation_data.max_columns_of_data = ncol`, which tells flopy to write full-shape external arrays and `sim.set_all_data_external(True)`.  With these two flags, you should be able to get going.

**Comment by leeaender** [comment]
WOHOOO. Awesome, thank you!
It works (or at least it does the same, as shown in your example - i still have to interpret/process the results :) )
I tried to do this for weeks now ;)
Many thanks for your fast advice!
