### ISSUE TITLE
Spatially locate parameters within a DISV-grid?

### ISSUE THREAD

**Issue by nikobenho** [pypest/pyemu#246]
Hi,

This is more of a question rather than an issue.

I'm following the example notebook from the repo [pyemu_pestpp_workflow](https://github.com/pypest/pyemu_pestpp_workflow).

This has helped me to get going with pmc (yay!).

However, my model is quite slow (~6 min runtime), which, with 100 or more realizations basically renders my laptop unusable for a couple of hours. I have developed a copy of this model, using the MF6 Disv grid (discretization by vertices). This model employs a much coarser grid and is only refined at important locations. All else equal, this model runs much faster.

To my question:
Is it possible to use a Disv model with PyEMU? I guess this (possibly among other things) require a different way of spatially locating parameters, compared with the function `pyemu.helpers.SpatialReference` which is based on the regular Dis convention?

Thanks!

Edit: I'm referring to a model I'm developing (not the Freyberg example, which ran quite fast!)

**Comment by jtwhite79** [comment]
We are just breaking into unstructured grid support.  So far, we have covered off a mf-usg model and I think it is also DISV.  You can see an example of how we did this for an mf-usg version of Freyberg here: [https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2840](https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2840 )

@rosskush added a class to read the GSF file, which is the key to locating the nodes spatially.  The trick is build up a dict of `{node:(x,y)}` for each layer and pass that as the `spatial_reference` for calls to `PstFrom` from array-type parameters, but the node number for array-type pars has to zero-indexed to the number of nodes in the layer, not the total number of nodes since the array-type input doesnt include a node-index list, its just a vector of numbers - yuck: 
[https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2891](https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2891)

But for list-style parameters, we just need the node-xy dict, which should be passed to the `PstFrom` constructor: [https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2947](https://github.com/pypest/pyemu/blob/e1ce35a34fa7c766f72f2a28b946be30c468bc13/autotest/pst_from_tests.py#L2947)

**Comment by nikobenho** [comment]
I see! I just started learning PEST/PESTPP and PyEMU through the GMDSI tutorials and jupyter notebooks, so with limited experience trying to navigate this landscape. I fancy having the entire workflow using notebooks if possible. I will give this a try and report back if i succeed (if not I'll just go with the dis-grid for now). Thanks!

**Comment by FrederickHoeckh** [comment]
Hi, 

I'm facing more or less the same issue. Are there any developments?

Thank you!

**Comment by jtwhite79** [comment]
PyPestUtils [https://github.com/pypest/pypestutils](https://github.com/pypest/pypestutils) been released and it handles the DISV stuff much better.  There are some high-level examples of using it with an mf6 quadtree grid and PstFrom.  If you need something specific to usg, you can just call the lower level py functions using grid xys and pilot points xys...
