### ISSUE TITLE
draw() error, spectral simulation

### ISSUE THREAD

**Issue by oscarfasanchez** [pypest/pyemu#300]
Hello! 
I'm here to report an error, or maybe to request a feature 😅
I have a modflow 6 model with an structured iregular grid
![image](https://user-images.githubusercontent.com/39230212/137553724-87343fea-7278-4255-b447-5366cb7c21d2.png)
when I try to use the following code:
    pe = pf.draw(300, use_specsim=True)     
    pe.to_binary(os.path.join(template_ws, "prior.jcb"))
I get 
Exception: draw() error: can't use spectral simulation with irregular grid

thanks for your attention

**Comment by jtwhite79** [comment]
@oscarfasanchez unfortunately, spectral sim only works for regular grids. But you can trick it into working by making an erroneous spatial reference that is regular grid - the spacing of the erroneous spatial reference should be the minimum spacing in your actual grid so that the geostats are correct for the area of interest and this erroneous spatial reference should have the same number of rows and columns as actual model.  Something like

```
mn = min(m.dis.delr.data.min(),m.dis.delc.data.min())
delr = [mn for _ in range(m.dis.ncol.data)]
delc = [mn for _ in range(m.dis.nrow.data)]
sr = pyemu.helpers.SpatialReference(delr=delr,delc=delc)
pf.add_parameters("hk.dat",par_type="grid",sr=sr)
```
That should trick `SpecSim` into complying. The geostats will be overly correlated in the large cells but maybe that is ok since the area of interest has the correct geostats? Otherwise, if the number of active cells is less than about 30K, you might be able to get by without specsim and just using standard covariance decomposition approach...that takes some memory though...let us know if that works...

**Comment by oscarfasanchez** [comment]
hello!, thanks for your answer
i just skipped the drawing step, and I'm assuming that Pestpp-ies does it by itself(using standard covariance decomposition approach? 😅), I don't have many parameters, so I think i'll be fine by now.
thank you very much!
