### ISSUE TITLE
Couldn't access the input/output files when PEST runs

### ISSUE THREAD

**Issue by MostafaGomaa93** [pypest/pyemu#303]
Error:
**control file parsing error: error in model interface file access:Could not access the following model interface files: temp_files\obs_simulated_heads.txt.ins,
temp_files\obs_simulated_heads.txt,
temp_files\steady_state.npf_k_lay1.txt.tpl,
temp_files\steady_state.npf_k_lay1.txt**

I feel it's a silly mistake of mine but I try many times but no success. Although It's not my first PEST model, I couldn't know where is exactly the problem. I already check the MODFLOW forward run (without PEST) and it's run successfully. I attach the script and the model files in the link (https://we.tl/t-nKm4DThkRu) and would appreciate it if you can check them

Another thing, Is there a way to generate the forward_run.py with the updated location of the obs file?. If you open my script "steady_state_ex.py"

When I don't add line 60 (add the forward_run.py), the generated forward_run.py is not complete. It will be:

def main():
    pyemu.os_utils.run(r'mf6')

if __name__ == '__main__':
    mp.freeze_support()
    main()

But, after adding line 60 in my script, the forward_run.py will be:

def main():
    try:
       os.remove(r'temp_files\obs_simulated_heads.txt')
    except Exception as e:
       print(r'error removing tmp file:temp_files\obs_simulated_heads.txt')
    pyemu.helpers.apply_list_and_array_pars(arr_par_file='mult2model_info.csv',chunk_len=50)
    pyemu.os_utils.run(r'mf6')

if __name__ == '__main__':
    mp.freeze_support()
    main()

**Comment by jtwhite79** [comment]
ok, this looks to be a pathing issue (again...).  In `pest_control.pst`, the "* model input/output" are meant to be in a "temp_files" files directory (like `temp_files\steady_state.npf_k_lay1.txt.tpl`).  This means there needs to be a "temp_files" directory from the location where `pestpp-xxx` is running.  So this means you need to run `pestpp-xxx` at the same directory level as "temp_files" and "model_files".  Ok, so I did that but that doesnt work either because some of the files that "forward_run.py" is looking for are not fully pathed.  So you need to rectify this some how.  I personally like to have all the model+pest files in one flat directory so that I can more easily use the parallel run manager.  

In this case, you dont really need pstfrom, you can just build the control file using the template and instruction files directly.  Ive done this in the attached script.  Its still not running because the template files for npf k dont have the right format/number of values compared to what mf6 is expecting.  But this should help you keeping going - just modify the tpl files and the rerun the script.
[steady_state_ex.py.zip](https://github.com/pypest/pyemu/files/7583187/steady_state_ex.py.zip)
..

**Comment by MostafaGomaa93** [comment]
It works! Thanks a lot.

But I have two more questions:
1- So, if in the npf file, let say for ex: if the num of parameters is 1000, but if I only want to select some of them to be included in the PEST run and not all of them. From what I understand from you, I should prepare the tpl file with same number of parameters, so in this ex will be 1000 and those that I don't want them to be included in the PEST run, I need to make them of type 'fixed', Correct?

2- In the example I attached, in the npf file, the number of parameters = 23302. The generated pest_control file (like this one, [pest_control.zip](https://github.com/pypest/pyemu/files/7583783/pest_control.zip)) will be a bit big file (with many lines), and therefore, the pest_control file will split the information into a group of csv files (one for the parameters, one for the observations, etc).

Is there anyway to avoid this? Its more handly to keep all the information in one file.
