### ISSUE TITLE
Passing valid spatial reference to .calc_factors_grid() method

### ISSUE THREAD

**Issue by Smith0710** [pypest/pyemu#309]
Hi

A spatial reference from the `flopy.utils.reference.SpatialReference()` class is passing successfully to `pyemu.geostats.OrdinaryKrige().calc_factors_grid()` although depreciation warnings occur when the spatial reference object is instanciated. The warning recommends `StructuredGrid` is used instead.

On the other hand, a spatial reference from the `flopy.discretization.structuredgrid.StructuredGrid()` class is not passing successfully to `pyemu.geostats.OrdinaryKrige().calc_factors_grid()` and generates an attribute error: 'StructuredGrid' object has no attribute 'xcentergrid'.

Thanks

**Comment by jtwhite79** [comment]
This is because flopy moved to the `modelgrid` class and apparently this required renaming otherwise identical attributes for some reason I havent yet figured out...But you can create a `pyemu.helpers.SpatialReference` instance using model georef info (lower left xy and rotation) and delr /delc arrays.  Then you can pass that to the geostats routines.

**Comment by Smith0710** [comment]
Thanks very much @jtwhite79. I am still finding my way around flopy and pyemu and don't always look in the right places. Appreciate your help. Cheers.
