### ISSUE TITLE
How to build and get results of PESTPP script with "mfnwt" from flopy?

### ISSUE THREAD

**Issue by inwoo-park** [pypest/pyemu#332]
Hi, developers.

I tried to use  `pyemu` for building `pest.pst` script with "mfnwt" package and `flopy`. First, I build the modflow model with flopy, and do not touch  scripts from flopy(*.nam, *.wel, *.obs). I look up how to build pest script, and find that `pstfrom_mf6.ipynb` in `examples` directory shows how to build pest script with `PstFrom` function. However, its seems that it only supports `mf6`, not `mfnwt`.

I have several question with using `pyemu`

Question) Can I build pest++ with `mfnwt`?

I think that initial `mf6` model script of `freyberg6` is not written in `flopy` , and therefore I got several errors in building pest script with flopy. In `pstfrom_mf6.ipynb` script, `add_parameters` and `add_observations` load `.txt` or `.csv` files for simulating `pestpp`. If I generate default modflow with flopy, I cannot operate pestpp with `PstFrom` option.

Or I think I can temperature parameter `.ins` file with `flopy.pest` module. Although I generate template file, I do not know how to import `.ins`. How to import parameter `.ins`?

* write template file with `flopy.pest` at `flopy/examples/Notebooks/flopy3_PEST.ipynb`
```python
mfpackage = "lpf"
partype = "hk"
parname = "HK_LAYER_1-3"

# Span indicates that the hk parameter applies as a multiplier to layers 0 and 2 (MODFLOW layers 1 and 3)
span = {"layers": [0, 2]}

# These parameters have not affect yet, but may in the future
startvalue = 10.0
lbound = 0.001
ubound = 1000.0
transform = "log"

p = flopy.pest.Params(
    mfpackage, partype, parname, startvalue, lbound, ubound, span
)
tw = flopy.pest.templatewriter.TemplateWriter(m, [p])
tw.write_template()
```

Question) How can I load results from `pestpp-ies`?

When I test `pstfrom_mf6.ipynb` with `pestpp-ies`, it does not generate several ensembles. How can I add `ensemble` option in pyemu? Also, how can I get results from `pestpp-ies`?

Best regards,
Inwoo

**Comment by mnfienen** [comment]
Hi @inwoo-park 

To your first question, `PstFrom` is actually model-agnostic. It works on external lists and arrays. So, if you build a `mfnwt` model in `flopy` just make sure you set the `external_path` argument so that all arrays are external files. HEre's some background https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_external_file_handling.ipynb

Once you do that, the MF6 examples with `PstFrom` should be easily adaptable.

For your second question, almost all the `pestpp-ies` files are in `csv` format and they are easily read by Excel and `pandas`.

Finally, if `pestpp=ies` is not writing an ensemble out, that likely means you are running the the setting `noptmax=0` which only writes a single realization. If you search here https://github.com/usgs/pestpp/blob/master/documentation/pestpp_users_manual.md for `NOPTMAX` you will see the meanings of various settings for pestpp-ies.

Hope this helps!

**Comment by inwoo-park** [comment]
Hi, @mnfienen

First, I find that `flopy` support writing `open/close` with `.txt` file format data. I confirm that `pestpp-ies` can modify the result of `modflow` parameters, and estimate each parameter.

Second, I find that `NOPTMAX` means `number of optimization iterations`. When I set `NOPTMAX > 0`, `pestpp-ies` generate several iteration files.

```python
import pyemu
pst = pyemu.Pst('temp.pst')
pst.control_data.noptmax = 3 # set number of optimization iterations.
```

Finally, when we I looked up the `*.par.csv` results file of `pestpp-ies`, it is hard to allocate each estimated values to specific parameters. Is there any function to generate estimated parameters with "*.par.csv" file?

Best regards,
Inwoo

**Comment by inwoo-park** [comment]
Hi, @mnfienen

Thank you for your kind replies.

I generally parameterize the hydraulic conductivity (hk), specific storage (ss), and constant head boundary value (CHD package in MODFLOW-package) with `multipliers`. The last esimated parameters from `{last}.par.csv` are as following:

```
real_name,p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13
0,0.195351,0.361368,2.37028,0.518838,1.27102,0.246682,5.81212,0.908726,1.3279,2.30747,1.41935,0.618737,1.188,0.628268
1,0.258034,0.268718,10,3.9887,1.15052,0.0410281,9.79131,0.590617,0.628029,7.65884,1.41496,0.383901,0.769798,1.398
2,0.036537,0.0821227,7.34265,2.03496,0.568276,0.115449,6.64401,4.42034,1.79627,2.75335,0.559412,1.33511,1.01523,1.09144
...............
base,0.751728,1.20081,8.9141,1.0504,0.996918,0.111369,6.22751,1.29721,0.549242,2.45059,0.479855,0.581094,1.00587,1.19917
```


However, I do not understand a meanings that  
>  run once with NOPTMAX=0 to generate a full suite of base model parameters `NOPTMAX=0` 

In `{last}.par.csv`, I figure out meanings of each parameter, such as p0, p1, p3 ... with `multpilers` method. For example, to get true value of specific parameter `p0` with `0-th` realization with value of `0.19xxx`, I have to multiply  `0.19xxxx` to original values. However, I do not understand the last row, `base`.

However, when I operate `pestpp-ies` with `NOPTMAX=0`, it does not reflect results from  `{last}.par.csv`. How to reflect that values?

In addition to, What does it means "to use base parameters rather than multipliers in PstFrom"?

Best regards,
Inwoo

**Comment by mnfienen** [comment]
Hi @inwoo-park - apologies, I was assuming you were confused about the use of multipliers, but clearly you understand that. So, the `base` realization is a special realization the `pestpp-ies` runs using all the starting values in the `parval1` column of the control file rather than a sampled ensemble. It's provided in case you are interested in a single realization that approximates the least-variance solution. But, it's optional to use it or not.

When I was suggesting using NOPTMAX=0, I was suggesting to set multipliers in the PST file to results of a realization and then run the whole model stack to convert from multipliers to actual values. However, you do not need to do that.

Finally, using base parameters (sorry for multiple uses of the word "base") is an option in `PstFrom` to not use multipliers. Sounds like you are already comfortable with multipliers, so don't worry about that.

Cheers
Mike

**Comment by wkitlasten** [comment]
Hey @inwoo-park, to add a little detail to @mnfienen 's comment, just in case it wasn't entirely clear: if you update parval1 in the pest control file with the final "base" parameter vector (minimum variance solution), then run pest with noptmax = 0 all the mfnwt files should be generated with the "actual values" such as K, Ss, etc. if using pandas and pyemu something like:

par.loc[:,'parval1'] = pe.loc['base',:]
pst.control_data.noptmax = 0
pst.write('base_N.pst')
