### ISSUE TITLE
Parameter and Observation ordering

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [pypest/pyemu#409]
Hi,
I found the PstFrom organize parameters and observations in an arbitrary order making it harder to update them using pandas.
Is there a way to align them with the order in the observation and parameter files so I can do column swapping easily?
Many thanks,
Daniel

![image](https://user-images.githubusercontent.com/22897462/220798739-791f95cd-bea4-4ac9-8a66-72854cba88ee.png)
![image](https://user-images.githubusercontent.com/22897462/220799225-70c82c24-8f9d-49e9-8b7d-4215db9ea844.png)

![image](https://user-images.githubusercontent.com/22897462/220798756-a5986fe9-7b39-4f61-a8ca-0a503cd0980b.png)

**Comment by wkitlasten** [comment]
I always keep a unique identifier for all table based pars and obs.

In your case, is pst _from assigning the name "ob10" to the 1987 sample?

**Comment by Daniel-Trung-Nguyen** [comment]
Yes, here is the longname version of that. You can see the first obs is at the 10th location and the time series data is jumping around. I am using pyemu shipped with the GMDSI_notebooks

![image](https://user-images.githubusercontent.com/22897462/220809543-69d2d33f-1e87-4166-af53-be32d5dadb84.png)

**Comment by wkitlasten** [comment]
What does your pf.add_parameters() call look like?

**Comment by jtwhite79** [comment]
Im sure there are places where we are using sets/dicts for lookup speed which is why the order is not aligned with the interface files.

**Comment by briochh** [comment]
Hi @Daniel-Trung-Nguyen, Suspect that you are passed this issue now.
We are definitely making use for sets and dicts for lookup speed. This can disrupt ordering. This can be a bit of a gotcha but we generally align things (pars and obs) on the values of indicies. As a general rule, safer to slice and dice those dataframes using `loc` rather than `iloc` (and assuming some preservation of order). 
Will close this issue for now, reopen if still causing problems.
