### ISSUE TITLE
File distribution functionality in pestpp-glm

### ISSUE THREAD

**Issue by Paszka1** [pypest/pyemu#436]
Is there a `pest-hp style` file distribution functionality in `pest++glm` to start a new iteration using initial heads based on the best set of parameters from the previous iteration? I've used this `pest-hp` feature for calibrating `TOUGH` models and it could help as well with modflow 6 models.

**Comment by briochh** [comment]
Hi @Paszka1, Might be worth raising this one over at https://github.com/usgs/pestpp/issues, as it would need to be implemented within the PEST++ code, I think. @weskitlasten, might be interested in using this sort of magic too.

**Comment by wkitlasten** [comment]
@paszka1, I'm not aware of any functionality in pestpp. But I have played around with IC heads as parameters in IES, localized to "solver obs" such as the number of MF6 inner and/or outer iterations, simulation time, and mass balance errors. It seems to speed up the runs quite a bit, especially when the K field get really heterogeneous. I've even thrown in solver parameters (under_relaxation_theta, etc), also appropriately localized... but I gave up on that due to audible gasps.
