### ISSUE TITLE
read_pestpp_runstorage

### ISSUE THREAD

**Issue by cnicol-gwlogic** [pypest/pyemu#437]
Hi there,

I'm using pestpp-ies 5.2.4, and latest develop brancyh pyemu. I'm trying to recover from the .rns file info using read_pestpp_runstorage(). I seem to be seeing column names in the "obs" dataframe (simulated model equivalents) that are unordered, and the data do not seem to match the obs names (I can tell by the magnitude of many of the numbers). Infact, the first block of numbers appear to be specific yield values (!!) - weird, I know. And looking in the "par" dataframe, I see a bunch of weird stuff too.

I wonder if there has there been a change to the rns file format that pyemu is not dealing with (?). Any ideas?

Thanks a lot.

**Comment by jtwhite79** [comment]
Nothing has changed in the run storage in a while....thats scary tho.  I dont think the rns file would store names in pst file order - should be hash order instead.  Can you post the rns and the pst files  (and maybe par ensemble if that is relevant here) the somewhere so I can have a look?

**Comment by cnicol-gwlogic** [comment]
No worries thanks - see [here](https://groundwaterlogiccom-my.sharepoint.com/:u:/g/personal/chris_nicol_groundwaterlogic_com/EYR4FQkIVwdHqvuR2AOZomQBhkb-XGrd0rnk0POu3PZBKQ?e=6VQIE5). I wonder if it could be because I accidentally ctrl-c'd the manager (wrong window...oh god) - does pestpp dump to the rns file progressively as runs come in?

**Comment by jtwhite79** [comment]
got 'em - debugging now...

**Comment by jtwhite79** [comment]
ok the panic is now subsiding (Ive been frantically debugging how in the world could ies be working correctly is the run storage is goofed!).  Luckily, as you suspected (and I dismissed without thinking), it is a change that was made a while back: the length of the message passed back from the worker was extended from 41 chars to 1001 chars in pest++ but the pyemu reader for the rns files still has the 41 chars.  whew!  I'll open a pull request now.  Otherwise, you can just change the two "41"s to "1001"s on this line:

[https://github.com/pypest/pyemu/blob/684f68a62a5153c0093db3b7b840e4cc5b139436/pyemu/utils/helpers.py#L1262](https://github.com/pypest/pyemu/blob/684f68a62a5153c0093db3b7b840e4cc5b139436/pyemu/utils/helpers.py#L1262)

**Comment by cnicol-gwlogic** [comment]
Haha wow sorry to give you a heart attack @jtwhite79 - I figured too it was fine behind the scenes, seeing as pestpp works. Thanks heaps for sorting it out. I did start digging through the pestpp code to find the rns record format, but that's beyond me. Cheers again.
