### ISSUE TITLE
format of parameter data section

### ISSUE THREAD

**Issue by RyanConway91** [pypest/pyemu#452]
I am applying a dataframe to Pst.patameter_data and writing a .pst
```
pst_sub.parameter_data = pst_sub_new
pst_sub.write('ps_sub_swp.pst')
```
Some of my parameters have small values (~1e-8). When I write the .pst, these are written as 0s (dataframe on left, .pst on right):

![image](https://github.com/pypest/pyemu/assets/25184697/6eb7331c-fde3-4e31-9158-44be2543b39b)

Is there a way to switch to scientific notation?

**Comment by briochh** [comment]
Hi @RyanConway91, I am struggling to reproduce at this end on the develop branch. 

It looks like you are writing a version 1  control file, do you see the same behaviour if you use version=2 in that write statement (not this will only work with PEST++ variants)? 

I wonder if there is something funny with those dtypes in your dataframe? @jtwhite79, as far as I can see those columns should be getting parsed through **FFMT = lambda x: "{0:<20.10E} ".format(float(x))** right? So that should set everything to scientific notation. Pandas is now supporting mixed dtype columns (`object` type) -- I wonder if something is misbehaving there. Could you take a look at the dtypes of your dataframe and maybe of those individual data entires?

**Comment by jtwhite79** [comment]
I think @briochh is right - @RyanConway91 what are the dtypes in `pst_sub_new`?  A work around might be to use `pst_sub.parameter_data.loc[:,"parlbnd"] = pst_sub_new.loc[pst.par_names,"parlbnd"]`, which I think will preserve the dtype of the original `parameter_data` dataframe

**Comment by RyanConway91** [comment]
The dtypes seemed to be the issue. Remapping par values to numeric resulted in scientific notation in the .pst.

```
pst_sub_new[['parval1', 'parlbnd','parubnd']] = pst_sub_new[['parval1', 'parlbnd','parubnd']].apply(pd.to_numeric)
pst_sub.parameter_data = pst_sub_new

```
Thanks!
