### ISSUE TITLE
Justification for setting par_names to all lowercase in parse_tpl_file

### ISSUE THREAD

**Issue by gmerritt123** [pypest/pyemu#473]
Take this question/ask in good faith as I'm not as experienced using PEST++ as I'd like to be.

I'm initializing a pst instance using the `from_io` method, then I'm modifying the `parameter_data` attribute (it's just a dataframe). I'm modifying it according to how I want to set up the problem (make parameter groups, set transforms, initial values, bounds, etc.).

My annoyance is as follows. After looking through the source code, `from_io` calls `parse_tpl_file` to parse the template file inputs. Line 414 of --> https://github.com/pypest/pyemu/blob/develop/pyemu/pst/pst_utils.py sets all parnmes to lowercase:

`                par_line = set(line.lower().strip().split(marker)[1::2])`

So that means my `parameter_data` dataframe on my pst instance has the `parnme` field set to lowercase. Now I can't easily join/map back any other dataframes or dictionaries to it using `parnme` as the key, which means it's more of a PITA to map back all my desired initial parvals, bounds etc to it than (I think) it should be.

Ultimately I'm wondering what the justification is for setting `parnme` to lowercase in the `parse_tpl` method (there might be good reason I'm unaware of).

Thanks...

**Comment by cnicol-gwlogic** [comment]
In my experience it's more of a PITA finding the reason why two data sets won't merge properly, simply because someone somewhere along the line gave you some data with a bore id that starts with a "D" rather than a "d". And you usually find that after you've wasted a heap of pest compute time with shoddy i/o, and have to rerun it all once you weed out what/where the issue was. And by that stage your budget is gone, along with your sanity. 

I always strip case from all pest inputs these days by default to avoid this stuff. I'm guessing this is probably a similar reason to the original devs intemt.

**Comment by briochh** [comment]
spot on @cnicol-gwlogic, really the casting to lower() is to try and avoid case sensitivity within pyemu. There are a lot of places within the standard workflow with both PEST(++) and pyemu that relies on matching strings. We have found it generally safer to cast to ensure that we are not getting failed matches based on case. The choice of lower() is somewhat arbitrary, I think Jon Doherty's Groundwater Utils might default to UPPER, which is a fun twist. 

Happy to hear arguments for not casting or casting to UPPER but it would likely introduce a breaking change so would need to be carefully thought through!
