### ISSUE TITLE
testing issue

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#491]
Hey, trying to run autotests and I get:

```
(py39) C:\modelling\pyemu>pytest --basetemp=runner autotest
================================================= test session starts =================================================
platform win32 -- Python 3.9.18, pytest-7.1.3, pluggy-1.0.0
rootdir: C:\modelling\pyemu\autotest, configfile: pytest.ini
plugins: flaky-3.7.0
collected 217 items
```

heaps of fails, starting with:

`FileNotFoundError: [Errno 2] No such file or directory: 'pst\\pest.pst'`

The file exists here: `pyemu\autotest\pst\pest.pst`

My only guess is that the tests need to be run from within the autotest dir, but then I get `ERROR: file or directory not found: autotest`. Any suggestions?

**Comment by briochh** [comment]
I think you have it right @weskitlasten, the tests are setup to be run from within the autotest directory.
The issue might be that you are not updating your run command when running from autotest.
Should be:
`pytest --basetemp=runner '.'`

Note, consider using [pytest-xdist](https://pytest-xdist.readthedocs.io/en/latest/) so that you can run the tests in parallel by adding the option `-n auto`

**Comment by wkitlasten** [comment]
thanks
