### ISSUE TITLE
shortnames may still violate template file line length constraints in pest_hp

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#500]
Just ran into a line length limit (2000) in template files for pest_hp after converting from longnames and version=2 to short names and version=1. This is how I resolved it on my end... no doubt someone else can do it better, faster, and put it in the proper place within pyemu:

```
    for fname in pst.template_files:
        print(f'checking template file line length: {fname}')
        with open(os.path.join(model_ws, fname), 'r') as fcheck:
            lines = fcheck.readlines()
        for line in lines:
            nloop = 0
            while len(line) > 2000 and nloop<100:
                line = line.replace('~  ', '~ ') # 2 spaces to 1 space
                line = line.replace('  ~', ' ~')
                nloop = nloop+1
            assert nloop<100, f"could not reduce line length in {fname}"
        with open(os.path.join(model_ws, fname), 'w') as fcheck:
            for line in lines:
                fcheck.write(line)
```

**Comment by briochh** [comment]
Unfortunately, that 2000 line limit is a bit of a barrier to building .tpl files for "full-width" array like files (as is done with pstfrom). Even if your par names are only 10 chars, you'll only be able to fit 200 on a line (absolute max with no delimiter). Be careful if you are reducing the length of the chars between those '~' tags. If too small your par changes will be lost due to lack of precision.

**Comment by wkitlasten** [comment]
I agree, once again, it is probably best to just let it fail and have the user adjust for their particular situation or get the 2000 line limit changed. My dream of simple push button modelling dies once more!
