### ISSUE TITLE
pst_helper - processing a different number of wells in each stress period

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#84]
Hello,

I'm trying to run the pst_helper on an existing model that has a different (increasing) number of wells in each stress period. I get the following error:

Exception: spatial_list_pars() error: must have same number of entries for every stress period for wel

I've done the obvious fix of re-writing my model .wel file to run all wells in all stress periods, some with zero pumping rates. But that's a bit painful and I'm a bit lazy. 

I wonder how common this is in other models, and whether it is worth developing a fix to re-write the .wel file to the appropriate format. I suspect it would take about 3 lines of code. I also suspect that I could probably do this if it annoys me enough and if I can find a few spare minutes. I'll schedule it in for 2021. :)

Cheerio,
Rebecca

**Comment by jtwhite79** [comment]
great question @RebeccaDoble - the helper needs the same number of BC for each stress period so we can apply element-by-element parameters (spatial list props) - otherwise, things can get goofed.  I can look into rectifying the issue automatically when in the helper routines.  or if you wanna do it, that would be sweet!

**Comment by RebeccaDoble** [comment]
Happy either way, although with me it will take a while. My main objective is meeting milestones! I'm still trying to figure out how to deal with 'wrong number of pp_files found:{0}'   :(
